export const list = {
  periodList: [
    { name: 'Tháng 1', value: 'Thang 1' },
    { name: 'Tháng 2', value: 'Thang 2' },
    { name: 'Tháng 3', value: 'Thang 3' },
    { name: 'Tháng 4', value: 'Thang 4' },
    { name: 'Tháng 5', value: 'Thang 5' },
    { name: 'Tháng 6', value: 'Thang 6' },
    { name: 'Tháng 7', value: 'Thang 7' },
    { name: 'Tháng 8', value: 'Thang 8' },
    { name: 'Tháng 9', value: 'Thang 9' },
    { name: 'Tháng 10', value: 'Thang 10' },
    { name: 'Tháng 11', value: 'Thang 11' },
    { name: 'Tháng 12', value: 'Thang 12' },
    { name: 'Quý 1', value: 'Quy 1' },
    { name: 'Quý 2', value: 'Quy 2' },
    { name: 'Quý 3', value: 'Quy 3' },
    { name: 'Quý 4', value: 'Quy 4' },
    { name: 'Năm', value: 'Nam' },
  ],
  tabList: [
    { name: 'Xã tổng hợp', value: 'Xa tong hop' },
    { name: 'Phòng thuộc Huyện tổng hợp', value: 'Phong thuoc huyen tong hop' },
    { name: 'Phòng TC-KH báo cáo', value: 'Phong TC - KH bao cao' },
    { name: 'Văn phòng UBND Huyện', value: 'Van phong UBND Huyen' },
  ],
  mau_bao_cao_phong_thuoc_huyen: [
    { name: 'Báo cáo tổng hợp', value: 'Bao cao tong hop' },
    { name: 'Báo cáo theo các xã', value: 'Bao cao theo cac xa' },
  ],
  mau_bao_cao_phong_TC_KH: [
    { name: 'Chỉ tiêu tỉnh giao', value: 'Chi tieu tinh giao' },
    { name: 'Chỉ tiêu huyện giao', value: 'Chi tieu huyen giao' },
    { name: 'Chỉ tiêu phòng giao', value: 'Chi tieu phong giao' },
  ],
  mau_bao_cao_van_phong_huyen: [
    { name: 'Chỉ tiêu tỉnh giao', value: 'Chi tieu tinh giao' },
    { name: 'Chỉ tiêu huyện giao', value: 'Chi tieu huyen giao' },
  ],
  xa: [],
  fields: { text: 'name', value: 'value' },
};
